// This file was generated by @tanstack/router-plugin
// Will be regenerated by `vite` dev server / build

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as AuthRoute } from './routes/auth'
import { Route as DashboardRoute } from './routes/dashboard'
import { Route as NotesRoute } from './routes/notes'

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute,
  DashboardRoute,
  NotesRoute,
])
