const tokens = require("./src/theme/tailwind.tokens.generated.js");

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}", "./global.css"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: tokens.light.background,
        foreground: tokens.light.foreground,
        card: tokens.light.card,
        "card-foreground": tokens.light["card-foreground"],
        popover: tokens.light.popover,
        "popover-foreground": tokens.light["popover-foreground"],
        primary: tokens.light.primary,
        "primary-foreground": tokens.light["primary-foreground"],
        secondary: tokens.light.secondary,
        "secondary-foreground": tokens.light["secondary-foreground"],
        muted: tokens.light.muted,
        "muted-foreground": tokens.light["muted-foreground"],
        accent: tokens.light.accent,
        "accent-foreground": tokens.light["accent-foreground"],
        destructive: tokens.light.destructive,
        "destructive-foreground": tokens.light["destructive-foreground"],
        border: tokens.light.border,
        input: tokens.light.input,
        ring: tokens.light.ring,
        chart1: tokens.light["chart-1"],
        chart2: tokens.light["chart-2"],
        chart3: tokens.light["chart-3"],
        chart4: tokens.light["chart-4"],
        chart5: tokens.light["chart-5"],
        sidebar: tokens.light.sidebar,
        "sidebar-foreground": tokens.light["sidebar-foreground"],
        "sidebar-primary": tokens.light["sidebar-primary"],
        "sidebar-primary-foreground": tokens.light["sidebar-primary-foreground"],
        "sidebar-accent": tokens.light["sidebar-accent"],
        "sidebar-accent-foreground": tokens.light["sidebar-accent-foreground"],
        "sidebar-border": tokens.light["sidebar-border"],
        "sidebar-ring": tokens.light["sidebar-ring"],
        brandPurple: tokens.brand.purple,
        brandPink: tokens.brand.pink,
        brandBlue: tokens.brand.blue,
        brandOrange: tokens.brand.orange,
        brandGreen: tokens.brand.green,
      },
      borderRadius: {
        lg: tokens.radius,
        md: `calc(${tokens.radius} * 0.8)`,
        sm: `calc(${tokens.radius} * 0.6)`,
      },
    },
  },
  plugins: [],
};
