import {
  Globe,
  ShieldAlert,
  FileCheck2,
  Cpu,
  Zap,
  Database,
  Radio,
  CheckCircle,
} from "lucide-react";
import type { PipelineStep } from "./flow-pipeline-types";

export const getPipelineSteps: PipelineStep[] = [
  {
    stepNumber: 1,
    title: "Client HTTP Request",
    layer: "Presentation",
    icon: Globe,
    description: "React UI dispatches typed API query via @repo/api-client.",
    file: "packages/api-client/src/subclients/notes.ts",
    output: "GET /api/notes?page=1&limit=20",
  },
  {
    stepNumber: 2,
    title: "Gateway & Auth Guards",
    layer: "Presentation",
    icon: ShieldAlert,
    description: "AuthGuard verifies JWT token and TenantContext sets CLS.",
    file: "apps/api/src/common/guards/auth.guard.ts",
    output: "Authenticated Tenant Context",
  },
  {
    stepNumber: 3,
    title: "Zod Query Validation",
    layer: "Presentation",
    icon: FileCheck2,
    description: "NotesController runs ZodValidationPipe on query parameters.",
    file: "packages/contracts/src/schemas/pagination.schema.ts",
    output: "PaginationQueryDto",
  },
  {
    stepNumber: 4,
    title: "CQRS Query Handler",
    layer: "Application",
    icon: Cpu,
    description: "GetNotesQuery coordinates read logic returning neverthrow Result.",
    file: "apps/api/src/modules/notes/application/queries/get-notes.query.ts",
    output: "Dispatched Query Execution",
  },
  {
    stepNumber: 5,
    title: "Redis Cache-Aside Check",
    layer: "Infrastructure",
    icon: Zap,
    description: "Checks Redis for key. On hit, returns; on miss, queries PostgreSQL.",
    file: "apps/api/src/infrastructure/cache/cache.service.ts",
    output: "Cache Miss / DB Fallthrough",
  },
  {
    stepNumber: 6,
    title: "TenantScoped Drizzle SQL",
    layer: "Infrastructure",
    icon: Database,
    description: "TenantScopedRepository injects WHERE tenant_id filter into Drizzle ORM.",
    file: "apps/api/src/modules/notes/infrastructure/repositories/notes.repository.ts",
    output: "Filtered PostgreSQL Rows",
  },
  {
    stepNumber: 7,
    title: "Domain Mapping & Metrics",
    layer: "Infrastructure",
    icon: Radio,
    description: "NoteMapper converts rows to domain model; MetricsService records latency.",
    file: "apps/api/src/modules/notes/domain/mappers/note.mapper.ts",
    output: "Result.ok(PaginatedNotes)",
  },
  {
    stepNumber: 8,
    title: "HTTP 200 JSON Response",
    layer: "Presentation",
    icon: CheckCircle,
    description: "handleResult() maps ok(data) to Fastify HTTP 200 payload.",
    file: "apps/api/src/common/utils/presentation.utils.ts",
    output: "HTTP 200 OK (JSON)",
  },
];
